image:
  repository: ghcr.io/e-berger/pod-reloader
  pullPolicy: Always

replicaCount: 1

affinity: {}

serviceAccount:
  create: true
  name: pod-reloader

imagePullSecrets:
  - name: dockerconfigjson

frequencyCheckSeconds: 120
