image:
  repository: ghcr.io/e-berger/pod-reloader
  pullPolicy: Always

replicaCount: 1

nodeSelector:
  finalcad/context: finalcad-runner
  kubernetes.io/os: linux
  node.kubernetes.io/lifecycle: spot


tolerations:
  - key: dedicated
    value: "finalcad-runner"
    effect: NoSchedule

affinity: {}

serviceAccount:
  create: true
  name: pod-reloader

imagePullSecrets:
  - name: dockerconfigjson

securityContext:
  privileged: true
